name: Test it

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test my-no-sql-core      
        run: |
          cd my-no-sql-core
          cargo test

      - name: Test my-no-sql-core Master-Node feature      
        run: |
          cd my-no-sql-core
          cargo build --features master-node